{"name": "test_a[1-2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <test_pytest.Testyear object at 0x0000023599777E80>, input = 1, expr = 2, login = None\n\n    @pytest.mark.parametrize('input,expr',[(1,2),(2+4,6),(6*9,54)])\n    def test_a(self,input,expr,login):\n>       assert input ==expr\nE       assert 1 == 2\n\ntest_pytest.py:17: AssertionError"}, "attachments": [{"name": "stdout", "source": "2538539c-ad66-489d-996f-654bd68971c9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "input", "value": "1"}, {"name": "expr", "value": "2"}], "start": 1659517141999, "stop": 1659517141999, "uuid": "16d0caee-f901-4e71-b8d9-7fecd860315c", "historyId": "1219761f86286d2fd1666ab8f50c2c57", "testCaseId": "348d5f8434957af6b6711082501264e4", "fullName": "test_pytest.Testyear#test_a", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Testyear"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "44844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}