{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "@allure.story(\"中断功能\")\n    def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_allure.py:25: Exception"}, "start": 1659525532175, "stop": 1659525532175, "uuid": "0e0b07ad-db71-4124-bc42-d1cebde66eb5", "historyId": "985c3d972d231f87d0914b89f78754fd", "testCaseId": "cb41bd139e929d9eef92825c451cc27a", "fullName": "test_allure#test_broken", "labels": [{"name": "story", "value": "中断功能"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "43992-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}